### ISSUE TITLE
linux安装失败

### ISSUE THREAD

**Issue by AckyLin** [snail007/proxy_admin_free#14]
执行以下代码404
`curl -L https://raw.githubusercontent.com/snail007/proxy_admin_free/master/install_auto.sh | bash`

` % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to raw.githubusercontent.com:443; 拒绝连接
`

**Comment by snail007** [comment]
已经修复,多谢反馈.

**Comment by AckyLin** [comment]
你好，请问在管理后台如何添加以下配置：
`proxy sps -S http -T tcp -P 127.0.0.1:11197 -t tcp -p :11196 -h aes-256-cfb -j 123 --log proxy.log --daemon
`

**Comment by snail007** [comment]
自定义

**Comment by AckyLin** [comment]
> 自定义

谢谢，可以了。还有一个问题，如果我要配置以下三条转发规则：
```
USER-AGENT: NeteaseMusic*
DOMAIN-SUFFIX: 163.com
DOMAIN-SUFFIX: 126.net
```

是在dns功能解析转发规则里面添加吗？
不知道如何书写

**Comment by snail007** [comment]
hosts功能,看手册.
另外不支持USER-AGENT这种.

**Comment by AckyLin** [comment]
sps要自定义配置以下内容：
{BLOCKED} ： blocked
{DIRECT} ： direct

` proxy sps -S http -T tcp -P 127.0.0.1:11196 -t tcp -p :11197 -h aes-256-cfb -j 123 --max-conns-rate 0  {DIRECT}  报错`

**Comment by NormanBB** [comment]
@snail007  安装面板中出现错误，系统为debian 9 , 安装版本为最新版，在运行install 脚本中，日志：
```
>>> installing ... 

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/snail007/license/lic-checker.MacCode(0x103b1dc, 0x3, 0x2, 0xc420035840)
        /ext-go/6/src/github.com/snail007/license/lic-checker/checker.go:98 +0x1ea
github.com/snail007/proxy-admin/boot.initConfigFiles()
        /ext-go/6/src/github.com/snail007/proxy-admin/boot/boot.go:141 +0x1f9
github.com/snail007/proxy-admin/boot.init.0()
        /ext-go/6/src/github.com/snail007/proxy-admin/boot/boot.go:36 +0x39

```

**Comment by snail007** [comment]
不是正常机器，没有网卡信息。另外这是VIP版本不是free版本。

**Comment by NormanBB** [comment]
> 不是正常机器，没有网卡信息。另外这是VIP版本不是free版本。

的确不是正常机器。

我下载的是GitHub上的release，不是VIP版吧？从错误日志中就能看出版本？

**Comment by snail007** [comment]
当然可以，只有VIP版本才会有这些。
